name: Radon Code Complexity Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  radon:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Replace with your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install radon  # Add any other project-specific dependencies

    - name: Run Radon
      run: |
        radon cc . -s  # Computes cyclomatic complexity in the entire repository
